application: agestats
version: pre1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /count/?
  script: views.count
- url: /getdata/?
  script: views.getdata
- url: /
  script: views.hello